---
title: "Support Vector Machines in R"
author: "BIOS 635"
date: "4/1/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(caret)
library(e1071)
```

```{r}
cancer_data_reg <- read_csv("../data/cancer_reg.csv") %>%
  select(-avgAnnCount, -avgDeathsPerYear, -incidenceRate, -Geography, -binnedInc) %>%
  drop_na()

heart_disease_data <- read_csv("../data/heart_disease/Correct_Dataset.csv",
                               na = c("", "NA", "?"))  %>%
  mutate(heart_disease = 
           relevel(factor(ifelse(Target>0, "Yes", "No")), 
                   ref = "No")) %>%
  select(-X1, -Target) %>%
  drop_na()
```

# Support Vector Machine
## Regression
```{r}
# Create 60:40 split
set.seed(123)
tt_indices <- createDataPartition(y=cancer_data_reg$TARGET_deathRate,
                                  p=0.6, list=FALSE)
cancer_data_train <- cancer_data_reg[tt_indices,]
cancer_data_test <- cancer_data_reg[-tt_indices,]

# Try support vector regression with linear kernal
svr_fit <- svm(formula = TARGET_deathRate~., data=cancer_data_train, kernel="linear")
summary(svr_fit)

# Look at accuracy 
cancer_data_train$pred_target <- predict(svr_fit, newdata = cancer_data_train)
cancer_data_test$pred_target <- predict(svr_fit, newdata = cancer_data_test)

postResample(cancer_data_train$pred_target, cancer_data_train$TARGET_deathRate)
postResample(cancer_data_test$pred_target, cancer_data_test$TARGET_deathRate)

# We can also choose a different kernel, for example polynomial
svr_fit <- svm(formula = TARGET_deathRate~., data=cancer_data_train, kernel="polynomial")
summary(svr_fit)

# Look at accuracy 
cancer_data_train$pred_target <- predict(svr_fit, newdata = cancer_data_train)
cancer_data_test$pred_target <- predict(svr_fit, newdata = cancer_data_test)

postResample(cancer_data_train$pred_target, cancer_data_train$TARGET_deathRate)
postResample(cancer_data_test$pred_target, cancer_data_test$TARGET_deathRate)

# We haven't done any tuning, need to tune parameters
cancer_data_train <- cancer_data_train %>% select(-pred_target)
cancer_data_test <- cancer_data_test %>% select(-pred_target)

svr_tune <- tune(svm, TARGET_deathRate~., data=cancer_data_train, kernel ="linear", 
                 ranges=list(elsilon=seq(0,1,0.5), cost=1:5))
plot(svr_tune)
summary(svr_tune)

# Choose best model
best_linear_svm <- svr_tune$best.model

# Now predict
cancer_data_train$pred_target <- predict(best_linear_svm, newdata = cancer_data_train)
cancer_data_test$pred_target <- predict(best_linear_svm, newdata = cancer_data_test)

postResample(cancer_data_train$pred_target, cancer_data_train$TARGET_deathRate)
postResample(cancer_data_test$pred_target, cancer_data_test$TARGET_deathRate)

# What about polynomial?
# We haven't done any tuning, need to tune parameters
cancer_data_train <- cancer_data_train %>% select(-pred_target)
cancer_data_test <- cancer_data_test %>% select(-pred_target)

svr_tune <- tune(svm, TARGET_deathRate~., data=cancer_data_train, kernel ="polynomial", 
                 ranges=list(degree=c(2,3,4), coef0=c(0.1,0.5,1,2,3,4)))
plot(svr_tune)
summary(svr_tune)

# Now predict
cancer_data_train$pred_target <- predict(best_linear_svm, newdata = cancer_data_train)
cancer_data_test$pred_target <- predict(best_linear_svm, newdata = cancer_data_test)

postResample(cancer_data_train$pred_target, cancer_data_train$TARGET_deathRate)
postResample(cancer_data_test$pred_target, cancer_data_test$TARGET_deathRate)
```

## Classification
```{r}
# Create 60:40 split
set.seed(123)
tt_indices <- createDataPartition(y=heart_disease_data$heart_disease,
                                  p=0.6, list=FALSE)
hd_data_train <- heart_disease_data[tt_indices,]
hd_data_test <- heart_disease_data[-tt_indices,]

```