---
title: "Non-Linear Coding Examples"
author: "BIOS 635"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(mgcv)
library(splines)
library(ISLR)
library(caret)
```

```{r}
wage_data <- Wage # contained in ISLR package
```

# Polynomial regression
## Fitting model and computing line of best fit
```{r}
## Case 1: by hand
wage_data_edit <- wage_data %>%
  mutate(age_2=age^2,
         age_3=age^3,
         age_4=age^4)

quad_reg_fit <- lm(wage~age+age_2+age_3+age_4,
                   data=wage_data_edit)

# Add fitted line
wage_data_edit$predict_wage <- predict(quad_reg_fit)

ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Quadratic polynomial regression: fitted line computed 'by hand'")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

## Case 2: Using ploy()
quad_reg_fit <- lm(wage~poly(age, 4),
                   data=wage_data_edit)

# Add fitted line
wage_data_edit$predict_wage <- predict(quad_reg_fit)

ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Quadratic polynomial regression: fitted line computed using poly()")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)
```

## Tuning "degree" parameter
```{r}
## Set degrees being considered:
degrees <- 1:20
poly_reg_fit <- list()
error_rates_degrees <- list()

# Fit model for each degree considered, compute RMSE (on training in this ex.)
for(i in 1:length(degrees)){
  poly_reg_fit[[i]] <- lm(wage~poly(age, degrees[i]),
                   data=wage_data_edit)
  
  predict_wages <- predict(poly_reg_fit[[i]])
  residuals_wages <- wage_data_edit$wage-predict_wages
  rmse_poly_reg <- sqrt(mean(residuals_wages^2))
  mae_poly_reg <- mean(abs(residuals_wages))
  
  # Save in data frame
  error_rates_degrees[[i]] <-
    data.frame("RMSE"=rmse_poly_reg,
               "MAE"=mae_poly_reg,
               "degree"=degrees[i])
}

# Bind all degree-specific results together into single data frame/table
error_rates_degrees_df <- do.call("rbind", error_rates_degrees)
quad_reg_fit <- lm(wage~poly(age, 4),
                   data=wage_data_edit)

# Plot results as function of degree
ggplot(data=error_rates_degrees_df,
       mapping=aes(x=degrees, y=RMSE))+
  geom_point()+
  geom_line()+
  labs(title="RMSE (Root Mean Squared Error) by degree without data splitting")

# Line continuously decreases, though seems improvement after 3 or 4 is minimal
# For better assessment, split into training (60:40 split for ex)

# Fit model for each degree considered, compute RMSE (on training in this ex.)
poly_reg_fit <- list()
error_rates_degrees <- list()

tt_indicies <- createDataPartition(y=wage_data_edit$wage, p=0.6, list = FALSE)
wage_data_train <- wage_data[tt_indicies,]
wage_data_test <- wage_data[-tt_indicies,]

for(i in 1:length(degrees)){
  poly_reg_fit[[i]] <- lm(wage~poly(age, degrees[i]),
                   data=wage_data_train)
  
  predict_wages <- predict(poly_reg_fit[[i]], newdata = wage_data_test)
  residuals_wages <- wage_data_test$wage-predict_wages
  rmse_poly_reg <- sqrt(mean(residuals_wages^2))
  mae_poly_reg <- mean(abs(residuals_wages))
  
  # Save in data frame
  error_rates_degrees[[i]] <-
    data.frame("RMSE"=rmse_poly_reg,
               "MAE"=mae_poly_reg,
               "degree"=degrees[i])
}

# Bind all degree-specific results together into single data frame/table
error_rates_degrees_df <- do.call("rbind", error_rates_degrees)

# Plot results as function of degree
ggplot(data=error_rates_degrees_df,
       mapping=aes(x=degrees, y=RMSE))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept = min(error_rates_degrees_df$RMSE),
                              linetype="dashed", color="red")+
  geom_vline(xintercept = 
               which(error_rates_degrees_df$RMSE==min(error_rates_degrees_df$RMSE)),
                              linetype="dashed", color="red")+
  labs(title="RMSE (Root Mean Squared Error) by degree on test set")+
  theme_bw()
```

# Step-wise with linear regression
## Group-specific lines of best fit
```{r}
# Do based on year born
wage_data_edit <- wage_data %>%
  mutate(year_2005 = factor(as.numeric(I(year<2005))))

# Use interaction terms to have separate slopes per year born group
# We will use linear relationship for simplicity
piecewise_int_fit <-
  lm(wage~year_2005+age+year_2005*age,
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(piecewise_int_fit)

# Plot lines of best fit
# Add color-blind friendly color scale
cbp1 <- c("#009E73", "#E69F00")

ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage, color=year_2005))+
  geom_point()+
  labs(title="Piecewise w/ linear interaction: fitted line computed 'by hand'")+
  geom_line(mapping=aes(y=predict_wage),
            size=2)+
  scale_colour_manual(values=cbp1)+
  theme_bw()

# Sample isn't longitudinal -> age and year essentially identical (example just for illustration)
```

# Splines
## Linear Spline
```{r}
# By hand, single knot at 50
wage_data_edit <- wage_data %>%
  mutate(age_basis_2 = ifelse(age<50, 0, age-50))

# Use interaction terms to have separate slopes per year born group
# We will use linear relationship for simplicity
linear_spline_fit <-
  lm(wage~age+age_basis_2,
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(linear_spline_fit)

# Plot lines of best fit
# Add color-blind friendly color scale

ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Linear spline regression: fitted line computed 'by hand'")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

# Using bs function
linear_spline_fit <-
  lm(wage~bs(age, knots = 50, degree=1),
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(linear_spline_fit)

# Plot lines of best fit
ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Linear spline regression: using bs function")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)
```

## Cubic Spline
```{r}
# By hand, single knot at 50
wage_data_edit <- wage_data %>%
  mutate(age_2 = age^2,
         age_3 = age^3,
         age_basis_4 = ifelse(age<50, 0, (age-50)^3))

# Use interaction terms to have separate slopes per year born group
# We will use linear relationship for simplicity
cubic_spline_fit <-
  lm(wage~age+age_2+age_3+age_basis_4,
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(cubic_spline_fit)

# Plot lines of best fit
# Add color-blind friendly color scale

ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Cubic spline regression: fitted line computed 'by hand'")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

# Using bs function
cubic_spline_fit <-
  lm(wage~bs(age, knots = 50, degree=3),
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(cubic_spline_fit)

# Plot lines of best fit
ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Cubic spline regression: using bs function")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)
```

## Natural Cubic Spline

```{r}
# Fit using ns function (won't do by hand, not necessary)
natural_cubic_spline_fit <-
  lm(wage~ns(age, knots=c(50)),
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(natural_cubic_spline_fit)
ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Natural Cubic spline regression: single knot")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

# Try adding many knots
## 1, By hand
natural_cubic_spline_fit <-
  lm(wage~ns(age, knots=c(30, 50, 60)),
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(natural_cubic_spline_fit)
ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Natural Cubic spline regression: many knots")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

### Only slightly different
## 2, Automated knot locations
natural_cubic_spline_fit <-
  lm(wage~ns(age, df=1),
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(natural_cubic_spline_fit)
ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Natural Cubic spline regression: 1 auto. knot")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

natural_cubic_spline_fit <-
  lm(wage~ns(age, df=10),
     data=wage_data_edit)

wage_data_edit$predict_wage <- predict(natural_cubic_spline_fit)
ggplot(data=wage_data_edit,
       mapping=aes(x=age, y=wage))+
  geom_point()+
  labs(title="Natural Cubic spline regression: 10 auto. knots")+
  geom_line(mapping=aes(y=predict_wage), 
            color="blue",
            size=2)

### Again, many knots - > not very different (recall property of natural cubic spline and overfitting)
### Where are these knots being placed?
attr(terms(natural_cubic_spline_fit), "predvars")
### Can see at 10th percentile, 20th percentile, etc. when 10 knots specified
### ns() places knots at evenly spaced percentiles

### Can see further properties of your spline using the following:
terms(natural_cubic_spline_fit)

### And see slope parameter estimates using
natural_cubic_spline_fit

```